version: '3.7'

services:
  backend:
    build: .
    ports:
      - "8484:8484"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/formationharrington?autoReconnect=true&useSSL=false
    depends_on:
      - db


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formationharrington
    ports:
      - "3307:3306"
